# Generated by Django 5.1.15 on 2026-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Peito'), ('back', 'Costas'), ('legs', 'Pernas'), ('shoulders', 'Ombros'), ('arms', 'Braços'), ('core', 'Core'), ('full_body', 'Corpo inteiro')], max_length=20)),
                ('equipment', models.CharField(choices=[('barbell', 'Barra'), ('dumbbell', 'Halteres'), ('machine', 'Máquina'), ('cable', 'Cabo'), ('bodyweight', 'Peso corporal'), ('kettlebell', 'Kettlebell'), ('other', 'Outro')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['name'],
            },
        ),
    ]
