# Generated by Django 5.1.15 on 2026-04-26 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
